env:
    env_name: 'OriginalDoubleInvertedPendulum'
    max_episode_steps: 250

ac:
    target_entropy: -0.5
    num_grad_steps: 20

mbpo:
    rollout_schedule: [ 1, 15, 1, 1 ]
    num_total_epochs: 80
    num_warmup_samples: 500


